### ISSUE TITLE
Errors installing

### ISSUE THREAD

**Issue by sudy-super** [EleutherAI/gpt-neox#1009]
**Describe the bug**
It's throwing an error when I run the first install command.
I tried to install libaio but no improvement.

**To Reproduce**
1. Run ```pip install -r requirements.txt```

**Expected behavior**
Install of requirements and anything else it needs

**Environment (please complete the following information):**
 - GPUs: None(I will use CPU.)

**Error details**
```
Collecting deepspeed (from -r requirements/requirements.txt (line 2))
  Cloning https://github.com/EleutherAI/DeeperSpeed.git to c:\users\appdata\local\temp\pip-install-dfzo7sci\deepspeed_4286e8e35aed4af489aacd5964951d84
  Running command git clone --filter=blob:none --quiet https://github.com/EleutherAI/DeeperSpeed.git 'C:\Users\AppData\Local\Temp\pip-install-dfzo7sci\deepspeed_4286e8e35aed4af489aacd5964951d84'
  Resolved https://github.com/EleutherAI/DeeperSpeed.git to commit 22fda1e0ee462c2b411575dc954cc8a29d78a7b2
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      test.c
      LINK : fatal error LNK1181: Unable to open input file 'aio.lib'.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\AppData\Local\Temp\pip-install-dfzo7sci\deepspeed_4286e8e35aed4af489aacd5964951d84\setup.py", line 163, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\AppData\Local\Temp\pip-install-dfzo7sci\deepspeed_4286e8e35aed4af489aacd5964951d84\setup.py", line 51, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      Setting ds_accelerator to cuda (auto detect)
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by StellaAthena** [comment]
This can likely be fixed by running `sudo apt install libaio-dev`. However the bigger problem is that you don't have GPUs. You should not try to use this library on systems that do not contain GPUs, and we do not support doing so. This library is specifically designed for large scale multi-node GPU training.

**Comment by sudy-super** [comment]
I tried it on a machine with a GPU. (Since my machine's OS is Windows 11, I ran `pip install libaio-dev`.)
```
ERROR: Could not find a version that satisfies the requirement libaio-dev (from versions: none)
ERROR: No matching distribution found for libaio-dev
```

**Comment by StellaAthena** [comment]
What about just `libaio`

**Comment by sudy-super** [comment]
I get the same as the first error.

**Comment by sudy-super** [comment]
I ran it on a machine with linux installed and everything was resolved. It seems that flash attention only supports linux.
