### ISSUE TITLE
AssertionError: Not sure how to proceed, we were given deepspeed configs in the deepspeed arguments and deepspeed.initialize() function call

### ISSUE THREAD

**Issue by shaunstoltz** [EleutherAI/gpt-neox#1043]
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    pretrain(neox_args=neox_args)
  File "/home/shaunst/repo/gpt-neox/megatron/training.py", line 183, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(
  File "/home/shaunst/repo/gpt-neox/megatron/training.py", line 605, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/shaunst/repo/gpt-neox/venv/lib/python3.8/site-packages/deepspeed/__init__.py", line 146, in initialize
    assert config is None, "Not sure how to proceed, we were given deepspeed configs in the deepspeed arguments and deepspeed.initialize() function call"
AssertionError: Not sure how to proceed, we were given deepspeed configs in the deepspeed arguments and deepspeed.initialize() function call

**Comment by always-H** [comment]
Hi, how do you solve the problem in the end?
