### ISSUE TITLE
Failed to train

### ISSUE THREAD

**Issue by notooth1** [EleutherAI/gpt-neox#227]
I failed to train gpt-neox with Enron emails data set. Can anyone help?

```
gpt-neox$ ./deepy.py pretrain_gpt2.py -d configs small.yml local_setup.yml

INFO:ConfigMonster:Total number of GPUs determined to be: 1
4.0 4 1
INFO:ConfigMonster:GPT-NEOX config: {'wandb_group': 'K9EivTiRLyqTJCALDvtGbT', 'git_hash': '51892e4', 'pipe-parallel-size': 1, 'model-parallel-size': 1, 'num-layers': 12, 'hidden-size': 768, 'num-attention-heads': 12, 'seq-length': 2048, 'max-position-embeddings': 2048, 'norm': 'rmsnorm', 'pos-emb': 'none', 'no-weight-tying': True, 'scaled-upper-triang-masked-softmax-fusion': False, 'optimizer': {'type': 'Adam', 'params': {'lr': 0.0006, 'max_grad_norm': 1.0, 'betas': [0.9, 0.95]}}, 'zero_optimization': {'stage': 0, 'allgather_partitions': True, 'allgather_bucket_size': 500000000, 'overlap_comm': True, 'reduce_scatter': True, 'reduce_bucket_size': 500000000, 'contiguous_gradients': True, 'cpu_offload': False}, 'train_micro_batch_size_per_gpu': 4, 'data-impl': 'mmap', 'split': '949,50,1', 'checkpoint-activations': True, 'checkpoint-num-layers': 1, 'partition-activations': True, 'synchronize-each-layer': True, 'gradient_clipping': 1.0, 'weight-decay': 0, 'hidden-dropout': 0, 'attention-dropout': 0, 'fp16': {'fp16': True, 'enabled': True, 'loss_scale': 0, 'loss_scale_window': 1000, 'hysteresis': 2, 'min_loss_scale': 1}, 'train-iters': 320000, 'lr-decay-iters': 320000, 'distributed-backend': 'nccl', 'lr-decay-style': 'cosine', 'warmup': 0.01, 'save-interval': 10000, 'eval-interval': 1000, 'eval-iters': 10, 'log-interval': 100, 'steps_per_print': 10, 'keep-last-n-checkpoints': 4, 'wall_clock_breakdown': True, 'data-path': 'data/enron/enron_text_document', 'vocab-file': 'data/gpt2-vocab.json', 'merge-file': 'data/gpt2-merges.txt', 'save': 'checkpoints', 'load': 'checkpoints', 'tensorboard-dir': 'tensorboard', 'log-dir': 'logs', 'num_gpus': 1, 'train_batch_size': 4.0, 'gradient_accumulation_steps': 1, 'batch-size': 4}
[2021-04-12 02:07:08,606] [WARNING] [runner.py:121:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2021-04-12 02:07:08,606] [INFO] [runner.py:364:main] cmd = /home/notooth/anaconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 pretrain_gpt2.py --num-layers 12 --hidden-size 768 --num-attention-heads 12 --max-position-embeddings 2048 --attention-dropout 0 --hidden-dropout 0 --weight-decay 0 --batch-size 4 --checkpoint-activations --checkpoint-num-layers 1 --train-iters 320000 --log-interval 100 --tensorboard-dir tensorboard --no-weight-tying --pos-emb none --norm rmsnorm --lr-decay-style cosine --lr-decay-iters 320000 --warmup 0.01 --save checkpoints --save-interval 10000 --keep-last-n-checkpoints 4 --load checkpoints --model-parallel-size 1 --pipe-parallel-size 1 --distributed-backend nccl --eval-iters 10 --eval-interval 1000 --data-path data/enron/enron_text_document --split 949,50,1 --vocab-file data/gpt2-vocab.json --merge-file data/gpt2-merges.txt --seq-length 2048 --data-impl mmap --log-dir logs --partition-activations --synchronize-each-layer --wandb_group K9EivTiRLyqTJCALDvtGbT --git_hash 51892e4 --deepspeed --fp16 --gas 1 --zero-stage 0 --zero-reduce-scatter --zero-contiguous-gradients --zero-reduce-bucket-size 500000000 --zero-allgather-bucket-size 500000000 --clip-grad 1.0 --lr 0.0006 --adam-beta1 0.9 --adam-beta2 0.95 --adam-eps 1e-08 --momentum 0.0 --deepspeed_config {"train_batch_size":4.0,"train_micro_batch_size_per_gpu":4,"gradient_accumulation_steps":1,"optimizer":{"type":"Adam","params":{"lr":0.0006,"max_grad_norm":1.0,"betas":[0.9,0.95]}},"fp16":{"fp16":true,"enabled":true,"loss_scale":0,"loss_scale_window":1000,"hysteresis":2,"min_loss_scale":1},"gradient_clipping":1.0,"zero_optimization":{"stage":0,"allgather_partitions":true,"allgather_bucket_size":500000000,"overlap_comm":true,"reduce_scatter":true,"reduce_bucket_size":500000000,"contiguous_gradients":true,"cpu_offload":false},"steps_per_print":10,"wall_clock_breakdown":true,"deepspeed":true}
[2021-04-12 02:07:09,445] [INFO] [launch.py:82:main] WORLD INFO DICT: {'localhost': [0]}
[2021-04-12 02:07:09,445] [INFO] [launch.py:88:main] nnodes=1, num_local_procs=1, node_rank=0
[2021-04-12 02:07:09,445] [INFO] [launch.py:103:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2021-04-12 02:07:09,445] [INFO] [launch.py:104:main] dist_world_size=1
[2021-04-12 02:07:09,445] [INFO] [launch.py:112:main] Setting CUDA_VISIBLE_DEVICES=0
using world size: 1 and model-parallel size: 1 
using torch.float16 for parameters ...
-------------------- arguments --------------------
  adam_beta1 ...................... 0.9
  adam_beta2 ...................... 0.95
  adam_eps ........................ 1e-08
  adlr_autoresume ................. False
  adlr_autoresume_interval ........ 1000
  apply_query_key_layer_scaling ... False
  apply_residual_connection_post_layernorm  False
  attention_dropout ............... 0.0
  attention_softmax_in_fp32 ....... False
  batch_size ...................... 4
  bias_dropout_fusion ............. False
  bias_gelu_fusion ................ False
  checkpoint_activations .......... True
  checkpoint_in_cpu ............... False
  checkpoint_num_layers ........... 1
  clip_grad ....................... 1.0
  contiguous_checkpointing ........ False
  cpu_optimizer ................... False
  cpu_torch_adam .................. False
  data_impl ....................... mmap
  data_path ....................... data/enron/enron_text_document
  deepscale ....................... False
  deepscale_config ................ None
  deepspeed ....................... True
  deepspeed_activation_checkpointing  False
  deepspeed_config ................ {"train_batch_size":4.0,"train_micro_batch_size_per_gpu":4,"gradient_accumulation_steps":1,"optimizer":{"type":"Adam","params":{"lr":0.0006,"max_grad_norm":1.0,"betas":[0.9,0.95]}},"fp16":{"fp16":true,"enabled":true,"loss_scale":0,"loss_scale_window":1000,"hysteresis":2,"min_loss_scale":1},"gradient_clipping":1.0,"zero_optimization":{"stage":0,"allgather_partitions":true,"allgather_bucket_size":500000000,"overlap_comm":true,"reduce_scatter":true,"reduce_bucket_size":500000000,"contiguous_gradients":true,"cpu_offload":false},"steps_per_print":10,"wall_clock_breakdown":true,"deepspeed":true}
  deepspeed_mpi ................... False
  distribute_checkpointed_activations  False
  distributed_backend ............. nccl
  dynamic_loss_scale .............. True
  eod_mask_loss ................... False
  eval_interval ................... 1000
  eval_iters ...................... 10
  exit_interval ................... None
  finetune ........................ False
  fp16 ............................ True
  fp16_lm_cross_entropy ........... False
  fp32_allreduce .................. False
  gas ............................. 1
  geglu ........................... False
  git_hash ........................ 51892e4
  hidden_dropout .................. 0.0
  hidden_size ..................... 768
  hysteresis ...................... 2
  init_method_std ................. 0.02
  keep_last_n_checkpoints ......... 4
  layernorm_epsilon ............... 1e-05
  lazy_mpu_init ................... None
  load ............................ checkpoints
  local_rank ...................... 0
  log_dir ......................... logs
  log_interval .................... 100
  loss_scale ...................... None
  loss_scale_window ............... 1000
  lr .............................. 0.0006
  lr_decay_iters .................. 320000
  lr_decay_style .................. cosine
  make_vocab_size_divisible_by .... 128
  max_position_embeddings ......... 2048
  merge_file ...................... data/gpt2-merges.txt
  min_lr .......................... 0.0
  min_scale ....................... 1
  mmap_warmup ..................... False
  model_parallel_size ............. 1
  momentum ........................ 0.0
  no_load_optim ................... False
  no_load_rng ..................... False
  no_save_optim ................... False
  no_save_rng ..................... False
  no_weight_tying ................. True
  norm ............................ rmsnorm
  num_attention_heads ............. 12
  num_layers ...................... 12
  num_unique_layers ............... None
  num_workers ..................... 2
  onebitadam ...................... False
  onnx_safe ....................... None
  openai_gelu ..................... False
  override_lr_scheduler ........... False
  param_sharing_style ............. grouped
  params_dtype .................... torch.float16
  partition_activations ........... True
  pipe_parallel_size .............. 1
  pipe_partition_method ........... type:transformer
  pos_emb ......................... none
  profile_backward ................ False
  rank ............................ 0
  reset_attention_mask ............ False
  reset_position_ids .............. False
  rms_norm_epsilon ................ 1e-08
  rpe_max_distance ................ 128
  rpe_num_buckets ................. 32
  save ............................ checkpoints
  save_interval ................... 10000
  scaled_masked_softmax_fusion .... False
  scaled_upper_triang_masked_softmax_fusion  False
  scalenorm_epsilon ............... 1e-08
  seed ............................ 1234
  seq_length ...................... 2048
  short_seq_prob .................. 0.1
  sm3 ............................. False
  sparsity ........................ none
  split ........................... 949,50,1
  synchronize_each_layer .......... True
  tensorboard_dir ................. tensorboard
  tokenizer_type .................. GPT2BPETokenizer
  train_iters ..................... 320000
  use_checkpoint_lr_scheduler ..... False
  use_cpu_initialization .......... False
  vocab_file ...................... data/gpt2-vocab.json
  wandb_group ..................... K9EivTiRLyqTJCALDvtGbT
  wandb_team ...................... None
  warmup .......................... 0.01
  weight_decay .................... 0.0
  world_size ...................... 1
  zero_allgather_bucket_size ...... 500000000
  zero_contiguous_gradients ....... True
  zero_reduce_bucket_size ......... 500000000
  zero_reduce_scatter ............. True
  zero_stage ...................... 0
---------------- end of arguments ----------------
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)
> setting tensorboard ...
Killing subprocess 16888
Traceback (most recent call last):
  File "/home/notooth/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/notooth/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/Archive1/Downloads/gpt-neox/src/deepspeed/deepspeed/launcher/launch.py", line 179, in <module>
    main()
  File "/mnt/Archive1/Downloads/gpt-neox/src/deepspeed/deepspeed/launcher/launch.py", line 169, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/mnt/Archive1/Downloads/gpt-neox/src/deepspeed/deepspeed/launcher/launch.py", line 147, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/notooth/anaconda3/bin/python', '-u', 'pretrain_gpt2.py', '--local_rank=0', '--num-layers', '12', '--hidden-size', '768', '--num-attention-heads', '12', '--max-position-embeddings', '2048', '--attention-dropout', '0', '--hidden-dropout', '0', '--weight-decay', '0', '--batch-size', '4', '--checkpoint-activations', '--checkpoint-num-layers', '1', '--train-iters', '320000', '--log-interval', '100', '--tensorboard-dir', 'tensorboard', '--no-weight-tying', '--pos-emb', 'none', '--norm', 'rmsnorm', '--lr-decay-style', 'cosine', '--lr-decay-iters', '320000', '--warmup', '0.01', '--save', 'checkpoints', '--save-interval', '10000', '--keep-last-n-checkpoints', '4', '--load', 'checkpoints', '--model-parallel-size', '1', '--pipe-parallel-size', '1', '--distributed-backend', 'nccl', '--eval-iters', '10', '--eval-interval', '1000', '--data-path', 'data/enron/enron_text_document', '--split', '949,50,1', '--vocab-file', 'data/gpt2-vocab.json', '--merge-file', 'data/gpt2-merges.txt', '--seq-length', '2048', '--data-impl', 'mmap', '--log-dir', 'logs', '--partition-activations', '--synchronize-each-layer', '--wandb_group', 'K9EivTiRLyqTJCALDvtGbT', '--git_hash', '51892e4', '--deepspeed', '--fp16', '--gas', '1', '--zero-stage', '0', '--zero-reduce-scatter', '--zero-contiguous-gradients', '--zero-reduce-bucket-size', '500000000', '--zero-allgather-bucket-size', '500000000', '--clip-grad', '1.0', '--lr', '0.0006', '--adam-beta1', '0.9', '--adam-beta2', '0.95', '--adam-eps', '1e-08', '--momentum', '0.0', '--deepspeed_config', '{"train_batch_size":4.0,"train_micro_batch_size_per_gpu":4,"gradient_accumulation_steps":1,"optimizer":{"type":"Adam","params":{"lr":0.0006,"max_grad_norm":1.0,"betas":[0.9,0.95]}},"fp16":{"fp16":true,"enabled":true,"loss_scale":0,"loss_scale_window":1000,"hysteresis":2,"min_loss_scale":1},"gradient_clipping":1.0,"zero_optimization":{"stage":0,"allgather_partitions":true,"allgather_bucket_size":500000000,"overlap_comm":true,"reduce_scatter":true,"reduce_bucket_size":500000000,"contiguous_gradients":true,"cpu_offload":false},"steps_per_print":10,"wall_clock_breakdown":true,"deepspeed":true}']' died with <Signals.SIGILL: 4>.

```

**Comment by StellaAthena** [comment]
Unfortunately this stack trace provides basically no information about what happened. Is there any other info you can provide?

**Comment by notooth1** [comment]
I would love to provide more information, but I don't know specifically which information you need.
