### ISSUE TITLE
Bugs during Setup

### ISSUE THREAD

**Issue by ImmortalDi** [EleutherAI/gpt-neox#369]
I have everything set up on Google Drive and Colab, but keep getting errors. The smaller issues I was able to solve, but these two new ones are keeping me from getting forward for a couple of weeks. Since I am a Newbie it would really help me a lot if you could help me out, maybe you see something I am overlooking. 

Here is the entire code and output so far:

`from google.colab import drive
drive.mount('/content/drive')`

Mounted at /content/drive

`import torch 
print(torch.__version__)`

1.9.0+cu102

`pip install -r /content/drive/MyDrive/requirements.txt`

Collecting pybind11==2.6.2
  Downloading https://files.pythonhosted.org/packages/8d/43/7339dbabbc2793718d59703aace4166f53c29ee1c202f6ff5bf8a26c4d91/pybind11-2.6.2-py2.py3-none-any.whl (191kB)
     |████████████████████████████████| 194kB 30.8MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from -r /content/drive/MyDrive/requirements.txt (line 2)) (1.15.0)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from -r /content/drive/MyDrive/requirements.txt (line 3)) (2019.12.20)
Collecting numpy==1.20.2
  Downloading https://files.pythonhosted.org/packages/73/ef/8967d406f3f85018ceb5efab50431e901683188f1741ceb053efcab26c87/numpy-1.20.2-cp37-cp37m-manylinux2010_x86_64.whl (15.3MB)
     |████████████████████████████████| 15.3MB 186kB/s 
Obtaining deepspeed from git+git://github.com/EleutherAI/DeeperSpeed.git@2d6a0d3de1282aa77a86df1a0d2a7ffa8647790b#egg=deepspeed (from -r /content/drive/MyDrive/requirements.txt (line 5))
  Cloning git://github.com/EleutherAI/DeeperSpeed.git (to revision 2d6a0d3de1282aa77a86df1a0d2a7ffa8647790b) to ./src/deepspeed
  Running command git clone -q git://github.com/EleutherAI/DeeperSpeed.git /content/src/deepspeed
  Running command git checkout -q 2d6a0d3de1282aa77a86df1a0d2a7ffa8647790b
  Running command git submodule update --init --recursive -q
Collecting mpi4py==3.0.3
  Downloading https://files.pythonhosted.org/packages/ec/8f/bbd8de5ba566dd77e408d8136e2bab7fdf2b97ce06cab830ba8b50a2f588/mpi4py-3.0.3.tar.gz (1.4MB)
     |████████████████████████████████| 1.4MB 45.9MB/s 
Collecting wandb==0.10.28
  Downloading https://files.pythonhosted.org/packages/5c/ee/d755f9e5466df64c8416a2c6a860fb3aaa43ed6ea8e8e8e81460fda5788b/wandb-0.10.28-py2.py3-none-any.whl (2.1MB)
     |████████████████████████████████| 2.1MB 23.3MB/s 
Collecting einops==0.3.0
  Downloading https://files.pythonhosted.org/packages/5d/a0/9935e030634bf60ecd572c775f64ace82ceddf2f504a5fd3902438f07090/einops-0.3.0-py2.py3-none-any.whl
Collecting transformers==4.5.0
  Downloading https://files.pythonhosted.org/packages/81/91/61d69d58a1af1bd81d9ca9d62c90a6de3ab80d77f27c5df65d9a2c1f5626/transformers-4.5.0-py3-none-any.whl (2.1MB)
     |████████████████████████████████| 2.2MB 49.6MB/s 
Collecting tokenizers==0.10.2
  Downloading https://files.pythonhosted.org/packages/ae/04/5b870f26a858552025a62f1649c20d29d2672c02ff3c3fb4c688ca46467a/tokenizers-0.10.2-cp37-cp37m-manylinux2010_x86_64.whl (3.3MB)
     |████████████████████████████████| 3.3MB 24.3MB/s 
Collecting lm_dataformat==0.0.19
  Downloading https://files.pythonhosted.org/packages/83/b5/8d10bf5a8082921792bb09c9d591dfd622cf4a16fbb7e283cc921c5ffc50/lm_dataformat-0.0.19-py3-none-any.whl
Collecting ftfy==6.0.1
  Downloading https://files.pythonhosted.org/packages/ce/b5/5da463f9c7823e0e575e9908d004e2af4b36efa8d02d3d6dad57094fcb11/ftfy-6.0.1.tar.gz (63kB)
     |████████████████████████████████| 71kB 11.9MB/s 
Requirement already satisfied: torch>=1.2 in /usr/local/lib/python3.7/dist-packages (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5)) (1.9.0+cu102)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5)) (4.41.1)
Collecting tensorboardX==1.8
  Downloading https://files.pythonhosted.org/packages/c3/12/dcaf67e1312475b26db9e45e7bb6f32b540671a9ee120b3a72d9e09bc517/tensorboardX-1.8-py2.py3-none-any.whl (216kB)
     |████████████████████████████████| 225kB 55.6MB/s 
Collecting ninja
  Downloading https://files.pythonhosted.org/packages/1d/de/393468f2a37fc2c1dc3a06afc37775e27fde2d16845424141d4da62c686d/ninja-1.10.0.post2-py3-none-manylinux1_x86_64.whl (107kB)
     |████████████████████████████████| 112kB 56.3MB/s 
Requirement already satisfied: psutil in /usr/local/lib/python3.7/dist-packages (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5)) (5.4.8)
**ERROR: Could not find a version that satisfies the requirement triton==0.4.0 (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5)) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.4.1, 0.4.2, 1.0.0.dev20210502, 1.0.0.dev20210506, 1.0.0.dev20210508, 1.0.0.dev20210509, 1.0.0.dev20210510, 1.0.0.dev20210515, 1.0.0.dev20210516, 1.0.0.dev20210520, 1.0.0.dev20210521, 1.0.0.dev20210525, 1.0.0.dev20210601, 1.0.0.dev20210611, 1.0.0.dev20210614, 1.0.0.dev20210621, 1.0.0.dev20210622)
ERROR: No matching distribution found for triton==0.4.0 (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5))**

`pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690`

/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py:283: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Created temporary directory: /tmp/pip-ephem-wheel-cache-kx7k8w9f
Created temporary directory: /tmp/pip-req-tracker-t7mpde1_
Created requirements tracker '/tmp/pip-req-tracker-t7mpde1_'
Created temporary directory: /tmp/pip-install-gxns8blg
Collecting git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690
  Created temporary directory: /tmp/pip-req-build-6bmhwy_s
  Cloning https://github.com/NVIDIA/apex.git (to revision e2083df5eb96643c61613b9df48dd4eea6b07690) to /tmp/pip-req-build-6bmhwy_s
  Running command git clone -q https://github.com/NVIDIA/apex.git /tmp/pip-req-build-6bmhwy_s
  Running command git show-ref e2083df5eb96643c61613b9df48dd4eea6b07690
  Running command git rev-parse HEAD
  d06404fecab73f152c6cbb89ac2c2e9b7fc24124
  Running command git checkout -q e2083df5eb96643c61613b9df48dd4eea6b07690
  Running command git submodule update --init --recursive -q
  Added git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690 to build tracker '/tmp/pip-req-tracker-t7mpde1_'
    Running setup.py (path:/tmp/pip-req-build-6bmhwy_s/setup.py) egg_info for package from git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690
    Running command python setup.py egg_info

    torch.__version__  = 1.9.0+cu102

    running egg_info
    creating /tmp/pip-req-build-6bmhwy_s/pip-egg-info/apex.egg-info
    writing /tmp/pip-req-build-6bmhwy_s/pip-egg-info/apex.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-req-build-6bmhwy_s/pip-egg-info/apex.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-req-build-6bmhwy_s/pip-egg-info/apex.egg-info/top_level.txt
    writing manifest file '/tmp/pip-req-build-6bmhwy_s/pip-egg-info/apex.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-req-build-6bmhwy_s/pip-egg-info/apex.egg-info/SOURCES.txt'
    /tmp/pip-req-build-6bmhwy_s/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")
  Source in /tmp/pip-req-build-6bmhwy_s has version 0.1, which satisfies requirement apex==0.1 from git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690
  Removed apex==0.1 from git+https://github.com/NVIDIA/apex.git@e2083df5eb96643c61613b9df48dd4eea6b07690 from build tracker '/tmp/pip-req-tracker-t7mpde1_'
Skipping wheel build for apex, due to binaries being disabled for it.
Installing collected packages: apex
  Created temporary directory: /tmp/pip-record-7_5x9got
    Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6bmhwy_s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6bmhwy_s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-7_5x9got/install-record.txt --single-version-externally-managed --compile

    torch.__version__  = 1.9.0+cu102

    /tmp/pip-req-build-6bmhwy_s/setup.py:67: UserWarning: Option --pyprof not specified. Not installing PyProf dependencies!
      warnings.warn("Option --pyprof not specified. Not installing PyProf dependencies!")

    Compiling cuda extensions with
    nvcc: NVIDIA (R) Cuda compiler driver
    Copyright (c) 2005-2020 NVIDIA Corporation
    Built on Wed_Jul_22_19:09:09_PDT_2020
    Cuda compilation tools, release 11.0, V11.0.221
    Build cuda_11.0_bu.TC445_37.28845127_0
    from /usr/local/cuda/bin

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-6bmhwy_s/setup.py", line 171, in <module>
        check_cuda_torch_binary_vs_bare_metal(torch.utils.cpp_extension.CUDA_HOME)
      File "/tmp/pip-req-build-6bmhwy_s/setup.py", line 106, in check_cuda_torch_binary_vs_bare_metal
        "https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  "
    RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.2.
    In some cases, a minor-version mismatch will not cause later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your own risk).
    Running setup.py install for apex ... error
Cleaning up...
  Removing source in /tmp/pip-req-build-6bmhwy_s
Removed build tracker '/tmp/pip-req-tracker-t7mpde1_'
**ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6bmhwy_s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6bmhwy_s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-7_5x9got/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.**
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/req_install.py", line 888, in install
    cwd=self.unpacked_source_directory,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 275, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6bmhwy_s/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6bmhwy_s/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-7_5x9got/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Thanks in advance for taking your time, kind soul.

**Comment by StellaAthena** [comment]
The key is `RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.2.` You need to go through and make sure that all the Cuda extensions are being compiled with Cuda 10.2. We mention this in the readme
> First make sure you are in an environment with `torch>=1.8` installed. Then run `pip install -r requirements/requirements.txt`. You may need to change the version of `cupy-cudaxxx` to match your machine's cuda version.

**Comment by StellaAthena** [comment]
As for
```
ERROR: Could not find a version that satisfies the requirement triton==0.4.0 (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5)) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.4.1, 0.4.2, 1.0.0.dev20210502, 1.0.0.dev20210506, 1.0.0.dev20210508, 1.0.0.dev20210509, 1.0.0.dev20210510, 1.0.0.dev20210515, 1.0.0.dev20210516, 1.0.0.dev20210520, 1.0.0.dev20210521, 1.0.0.dev20210525, 1.0.0.dev20210601, 1.0.0.dev20210611, 1.0.0.dev20210614, 1.0.0.dev20210621, 1.0.0.dev20210622)
ERROR: No matching distribution found for triton==0.4.0 (from deepspeed->-r /content/drive/MyDrive/requirements.txt (line 5))
```
this will sometimes go away if you just run the installer several times. I've also had the code work perfectly well despite getting a similar error, so once you fix the other problem I would just try training a model.

**Comment by StellaAthena** [comment]
Closing due to inactivity. If the above comments do not solve your issue, feel free to reopen it.
