### ISSUE TITLE
'PipelineEngine' object has no attribute 'set_has_attention_mask'

### ISSUE THREAD

**Issue by HughPH** [EleutherAI/gpt-neox#535]
**Describe the bug**
Using Python 3.7, pytorch 1.10.0 py3.7_coda11.3_cudnn8.2.0_0 this exception is thrown from torch/nn/modules/module.py

**To Reproduce**
Cloned the repo, installed packages from requirements.txt
Made the following modification to 20B.yml:
```
  "pipe-parallel-size": 1,                                                                                                                                                              
  "model-parallel-size": 1,
```
Ran `python ./deepy.py generate.py configs/20B.yml`
GPU VRAM starts being used, then the exception occurs.

**Screenshots**
```
[2022-02-10 13:31:57,664] [INFO] [engine.py:151:__init__] RANK=0 STAGE=0 LAYERS=49 [0, 49) STAGE_PARAMS=20552994816 (20552.995M) TOTAL_PARAMS=20552994816 (20552.995M) UNIQUE_PARAMS=20552994816 (20552.995M)
 > number of parameters on model parallel rank 0: 20552994816
 > total params: 20,552,994,816
Traceback (most recent call last):
  File "generate.py", line 87, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/home/hugh/gptserv/gpt-neox/megatron/utils.py", line 435, in setup_for_inference_or_eval
    iteration=neox_args.iteration,
  File "/home/hugh/gptserv/gpt-neox/megatron/training.py", line 431, in setup_model_and_optimizer
    model.set_has_attention_mask(True)
  File "/home/hugh/anaconda3/envs/gptfinetune-new/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1178, in __getattr__
    type(self).__name__, name))
AttributeError: 'PipelineEngine' object has no attribute 'set_has_attention_mask'
```

**Environment (please complete the following information):**
- GPUs: Nvidia A6000, ECC disabled
- Configs:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
attrs                     21.3.0                   pypi_0    pypi
best-download             0.0.9                    pypi_0    pypi
binutils_impl_linux-64    2.33.1               he6710b0_7
binutils_linux-64         2.33.1              h9595d00_15
black                     20.8b1                   pypi_0    pypi
blas                      1.0                         mkl
brotlipy                  0.7.0           py37h27cfd23_1003
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.10.26           h06a4308_2
certifi                   2021.10.8        py37h06a4308_2
cffi                      1.15.0           py37hd667e15_1
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.9                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
configparser              5.2.0                    pypi_0    pypi
cryptography              36.0.0           py37h9ce1e76_0
cudatoolkit               11.3.1               h2bc3f7f_2
cython                    0.29.27                  pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7
dataproperty              0.54.2                   pypi_0    pypi
datasets                  1.17.0                   pypi_0    pypi
deepspeed                 0.5.8                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
dpcpp-cpp-rt              2022.0.1                 pypi_0    pypi
dynet                     2.1.2                    pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0
filelock                  3.4.2              pyhd3eb1b0_0
freetype                  2.11.0               h70c0345_0
frozenlist                1.2.0                    pypi_0    pypi
fsspec                    2021.11.1                pypi_0    pypi
fused-kernels             0.0.1                    pypi_0    pypi
gcc_impl_linux-64         7.3.0                habb00fd_1
gcc_linux-64              7.3.0               h553295d_15
giflib                    5.2.1                h7b6447c_0
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.26                   pypi_0    pypi
gmp                       6.2.1                h2531618_2
gnutls                    3.6.15               he1e5248_0
hjson                     3.0.2                    pypi_0    pypi
huggingface_hub           0.2.1              pyhd3eb1b0_0
idna                      3.3                pyhd3eb1b0_0
importlib-metadata        4.10.0                   pypi_0    pypi
importlib_metadata        4.8.2                hd3eb1b0_0
iniconfig                 1.1.1                    pypi_0    pypi
intel-cmplr-lib-rt        2022.0.1                 pypi_0    pypi
intel-cmplr-lic-rt        2022.0.1                 pypi_0    pypi
intel-opencl-rt           2022.0.1                 pypi_0    pypi
intel-openmp              2022.0.1                 pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9d                   h7f8727e_0
jsonlines                 2.0.0                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.33.1               h53a641e_7
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgfortran-ng            7.5.0               ha8ba4b0_17
libgfortran4              7.5.0               ha8ba4b0_17
libgomp                   9.3.0               h5101ec6_17
libidn2                   2.3.2                h7f8727e_0
libopus                   1.3.1                h7b6447c_0
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              9.3.0               hd4cf53a_17
libtasn1                  4.16.0               h27cfd23_0
libtiff                   4.2.0                h85742a9_0
libunistring              0.9.10               h27cfd23_0
libuv                     1.40.0               h7b6447c_0
libvpx                    1.7.0                h439df22_0
libwebp                   1.2.0                h89dd481_0
libwebp-base              1.2.0                h27cfd23_0
lm-dataformat             0.0.19                   pypi_0    pypi
lm-eval                   0.0.1                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1
mbstrdecoder              1.1.0                    pypi_0    pypi
mkl                       2022.0.1                 pypi_0    pypi
mkl-fft                   1.3.1                    pypi_0    pypi
mkl-service               2.4.0            py37h7f8727e_0
mkl_fft                   1.3.1            py37hd3c417c_0
mkl_random                1.2.2            py37h51133e4_0
mock                      4.0.3                    pypi_0    pypi
mpi                       1.0                       mpich
mpich                     3.3.2                hc856adb_0
mpich-mpicc               3.3.2                hf39692e_0
msgfy                     0.2.0                    pypi_0    pypi
multidict                 5.2.0                    pypi_0    pypi
multiprocess              0.70.12.2                pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
nagisa                    0.2.7                    pypi_0    pypi
ncurses                   6.3                  h7f8727e_2
nettle                    3.7.3                hbbd107a_1
ninja                     1.10.2.3                 pypi_0    pypi
numexpr                   2.7.2                    pypi_0    pypi
numpy                     1.21.0                   pypi_0    pypi
olefile                   0.46                     py37_0
openai                    0.6.4                    pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openssl                   1.1.1m               h7f8727e_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.5                    pypi_0    pypi
pathspec                  0.9.0                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pathvalidate              2.5.0                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.2           py37h06a4308_0
pluggy                    0.13.1                   pypi_0    pypi
portalocker               2.3.2                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyarrow                   6.0.1                    pypi_0    pypi
pybind11                  2.6.2                    pypi_0    pypi
pycountry                 20.7.3                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.6                    pypi_0    pypi
pysocks                   1.7.1                    py37_1
pytablewriter             0.58.0                   pypi_0    pypi
pytest                    6.2.3                    pypi_0    pypi
python                    3.7.11               h12debd9_0
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.10.1          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2021.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1
regex                     2021.11.10               pypi_0    pypi
rehash                    1.0.0                    pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
sacrebleu                 1.5.0                    pypi_0    pypi
sacremoses                0.0.46                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
sentencepiece             0.1.95           py37hd09550d_0
sentry-sdk                1.5.2                    pypi_0    pypi
setuptools                60.1.1                   pypi_0    pypi
shortuuid                 1.0.8                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.37.2               hc218d9a_0
sqlitedict                1.6.0                    pypi_0    pypi
subprocess32              3.5.4                    pypi_0    pypi
tabledata                 1.3.0                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tbb                       2021.4.0                 pypi_0    pypi
tcolorpy                  0.1.1                    pypi_0    pypi
tensorboardx              1.8                      pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.11               h1ccaba5_0
tokenizers                0.10.2                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.10.1               py37_cu113    pytorch
torchvision               0.11.2               py37_cu113    pytorch
tqdm                      4.62.3             pyhd3eb1b0_1
tqdm-multiprocess         0.0.11                   pypi_0    pypi
transformers              4.5.0                    pypi_0    pypi
triton                    0.4.2                    pypi_0    pypi
typed-ast                 1.5.2                    pypi_0    pypi
typepy                    1.3.0                    pypi_0    pypi
typing-extensions         3.10.0.2             hd3eb1b0_0
typing_extensions         3.10.0.2           pyh06a4308_0
ujson                     5.1.0                    pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wandb                     0.10.28                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.1                   pypi_0    pypi
x264                      1!157.20191217       h7b6447c_0
xxhash                    2.0.2                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
yarl                      1.7.2                    pypi_0    pypi
yaspin                    2.1.0                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7f8727e_4
zstandard                 0.15.2                   pypi_0    pypi
zstd                      1.4.9                haebb681_0
```

**Comment by HughPH** [comment]
Wrong version of deepspeed, but mpi4py was blocking this because it was not installing. I'm told I can avoid mpi4py by using the NCCL Deepspeed backend - but I don't know how to do that.

**Comment by HughPH** [comment]
Removing mpi4py from requirements.txt unblocked this for me, I then merged the checkpoint for 1 GPU and _It Works_ without doing anything special with Deepspeed.
