### ISSUE TITLE
Inference crash in interactive mode

### ISSUE THREAD

**Issue by Mistobaan** [EleutherAI/gpt-neox#538]
**Describe the bug**
Inference crash in interactive mode

**To Reproduce**
set to text_generation.yml to "interactive"

**Expected behavior**

**Proposed solution**
If you have an idea for how we can fix this problem, describe it here. 

**Screenshots**
```
<press enter to continue>    print_rank_0("Generated Text: " + generated_text)
UnboundLocalError: local variable 'generated_text' referenced before assignment
Killing subprocess 21255
Killing subprocess 21256
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/launcher/launch.py", line 179, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/launcher/launch.py", line 169, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.7/site-packages/deepspeed/launcher/launch.py", line 147, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
```

**Environment (please complete the following information):**
Google Cloud Debian, 2x A100

**Comment by cloudcell** [comment]
How to fix: 
[text_generation_utils.py.zip](https://github.com/EleutherAI/gpt-neox/files/8045838/text_generation_utils.py.zip)
use this file instead of the file
./megatron/text_generation_utils.py
or change line 762: insert the following line
generated_text = ""

**Comment by sdtblck** [comment]
Closing this, thanks for the fix @cloudcell
