### ISSUE TITLE
args.vocab_file is not None

### ISSUE THREAD

**Issue by tongjiaming** [EleutherAI/gpt-neox#614]
When I try to evaluate using the command like this
`./deepy.py evaluate.py ./configs/20B.yml --eval_tasks lambada piqa`

I get an error like this
> building GPT2BPETokenizer tokenizer ...
Traceback (most recent call last):
  File "/tmp/gpt-neox/evaluate.py", line 55, in <module>
    main()
  File "/tmp/gpt-neox/evaluate.py", line 35, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=False)
  File "/tmp/gpt-neox/megatron/utils.py", line 424, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/tmp/gpt-neox/megatron/neox_arguments/arguments.py", line 121, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/tmp/gpt-neox/megatron/tokenizer/tokenizer.py", line 38, in build_tokenizer
    assert args.vocab_file is not None
AssertionError
Killing subprocess 103

Could you tell me how to fix this?

**Comment by StellaAthena** [comment]
Please follow the instructions in the [README](https://github.com/EleutherAI/gpt-neox#using-a-pretrained-model)
