### ISSUE TITLE
Getting error while   trying to process my own custom dataset

### ISSUE THREAD

**Issue by whoislimshady** [EleutherAI/gpt-neox#626]
**Describe the bug**
i am trying to use my own custom dataset for training but while running process_data.py file on my json file i am getting error saying 
`> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)
Vocab size: 50257
Output prefix: ./data/mydataset
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 50257) with 47 dummy tokens (new size: 50304)
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/jsonlines/jsonlines.py", line 162, in read
    value = self._loads(line)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/preprocess_data.py", line 238, in <module>
    main()
  File "tools/preprocess_data.py", line 208, in main
    for i, (doc, bytes_processed) in enumerate(encoded_docs, start=1):
  File "tools/preprocess_data.py", line 184, in <genexpr>
    encoded_docs = (encoder.encode(doc) for doc in fin)
  File "tools/preprocess_data.py", line 162, in yield_from_files
    yield from yielder(fname, semaphore)
  File "tools/preprocess_data.py", line 155, in yielder
    for f in filter(lambda x: x, lmd.Reader(fname).stream_data()):
  File "/usr/local/lib/python3.7/dist-packages/lm_dataformat/__init__.py", line 129, in stream_data
    yield from self._stream_data(get_meta)
  File "/usr/local/lib/python3.7/dist-packages/lm_dataformat/__init__.py", line 165, in _stream_data
    yield from self.read_jsonl(f, get_meta, key=jsonl_key)
  File "/usr/local/lib/python3.7/dist-packages/lm_dataformat/__init__.py", line 242, in read_jsonl
    yield from handle_jsonl(rdr, get_meta, autojoin_paragraphs, para_joiner, key)
  File "/usr/local/lib/python3.7/dist-packages/lm_dataformat/__init__.py", line 105, in handle_jsonl
    for ob in jsonl_reader:
  File "/usr/local/lib/python3.7/dist-packages/jsonlines/jsonlines.py", line 204, in iter
    type=type, allow_none=allow_none, skip_empty=skip_empty
  File "/usr/local/lib/python3.7/dist-packages/jsonlines/jsonlines.py", line 167, in read
    raise exc from orig_exc
jsonlines.jsonlines.InvalidLineError: line contains invalid json: Expecting property name enclosed in double quotes: line 2 column 1 (char 2) (line 1)
0it [00:00, ?it/s]`

**To Reproduce**
1. try to process the given json object using process_data.py file  
`{
    "text": [
        {
            "prompt": "contain prompt",
            "completion": "contain completion"
        },
        {
            "prompt": "contain prompt",
            "completion": "contain completion"
        },
        {
            "prompt": "contain prompt",
            "completion": "contain completion"
        },
        {
            "prompt": "contain prompt",
            "completion": "contain completion"
        }
    ]
}`

**Environment (please complete the following information):**
 - GPUs: 4 A100

**Additional context**
i am newbie in terms of json object and all so please let me know how to remove this error

**Comment by StellaAthena** [comment]
`process_data.py` expects there to be a field called `text` (which you have) that contains a string (which you don't have, yours contains a list of dicts). One way to massage your data into this form would be to structure it like this:
```
{"text": "prompt 1: completion 1"}
{"text": "prompt 2: completion 2"}
{"text": "prompt 3: completion 3"}
{"text": "prompt 4: completion 4"}
{"text": "prompt 5: completion 5"}
```
Note that I've combined the contexts of your two separate fields into a single string here. Some form of preprocessing to combine prompts and completions will be necessary to use this function.

**Comment by whoislimshady** [comment]
@StellaAthena  thank you for helping
