### ISSUE TITLE
Data loader error when using example Enron training data

### ISSUE THREAD

**Issue by dashstander** [EleutherAI/gpt-neox#715]
When using the `small.yml` config and the default Enron dataset there is a data loader error.

The command run was: `python deepy.py train.py --conf_dir configs small.yml local_setup.yml`

Here is a copy of the stack trace:

```
Traceback (most recent call last):
  File "/fsx/dashiell/gpt-neox/train.py", line 27, in <module>
    pretrain(neox_args=neox_args)
  File "/fsx/dashiell/gpt-neox/megatron/training.py", line 106, in pretrain
    iteration = train(
  File "/fsx/dashiell/gpt-neox/megatron/training.py", line 573, in train
    loss_dict, skipped_iter = train_step(
  File "/fsx/dashiell/gpt-neox/megatron/training.py", line 488, in train_step
    loss = forward_step(
  File "/fsx/dashiell/gpt-neox/megatron/training.py", line 216, in forward_step
    tokens, labels, loss_mask, attention_mask, position_ids = get_batch(
  File "/fsx/dashiell/gpt-neox/megatron/training.py", line 182, in get_batch
    data = next(data_iterator)
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in default_collate
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 160, in <dictcomp>
    return elem_type({key: default_collate([d[key] for d in batch]) for key in elem})
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 149, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/fsx/dashiell/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 141, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [2049] at entry 0 and [198705720] at entry 16
```

**Comment by Quentin-Anthony** [comment]
Resolved by https://github.com/EleutherAI/gpt-neox/pull/835
