### ISSUE TITLE
yaml.parser.ParserError: while parsing a flow mapping

### ISSUE THREAD

**Issue by PierrickI3** [EleutherAI/gpt-neox#753]
**Describe the bug**
I am testing a simple custom dataset in Google Colab and I get this error:

```
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
fatal: not a git repository (or any of the parent directories): .git
NeoXArgs.from_ymls() ['/content/drive/MyDrive/Colab Notebooks/files/local_setup2.yml']
Traceback (most recent call last):
  File "./gpt-neox/deepy.py", line 28, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/content/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args
    neox_args = cls.from_ymls(
  File "/content/gpt-neox/megatron/neox_arguments/arguments.py", line 175, in from_ymls
    conf = yaml.load(conf_file, Loader=yaml.FullLoader)
  File "/usr/local/lib/python3.8/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/dist-packages/yaml/parser.py", line 549, in parse_flow_mapping_key
    raise ParserError("while parsing a flow mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a flow mapping
  in "/content/drive/MyDrive/Colab Notebooks/files/local_setup2.yml", line 2, column 1
expected ',' or '}', but got ':'
  in "/content/drive/MyDrive/Colab Notebooks/files/local_setup2.yml", line 27, column 14
```

**To Reproduce**
1. Open a new GPU-enabled colab
2. Run `!git clone https://github.com/EleutherAI/gpt-neox`
3. Run `!pip install -r ./gpt-neox/requirements/requirements.txt`
4. Run `!pip install -r ./gpt-neox/requirements/requirements-flashattention.txt`
5. Run `!python ./gpt-neox/tools/preprocess_data.py --input "/content/drive/MyDrive/Colab Notebooks/files/data.jsonl" --output-prefix "/content/drive/MyDrive/Colab Notebooks/files/mydataset" --vocab "/content/drive/MyDrive/Colab Notebooks/files/gpt2-vocab.json" --merge-file "/content/drive/MyDrive/Colab Notebooks/files/gpt2-merges.txt" --dataset-impl mmap --tokenizer-type GPT2BPETokenizer --append-eod`
6. Run `!python ./gpt-neox/deepy.py ./gpt-neox/train.py  "/content/drive/MyDrive/Colab Notebooks/files/local_setup2.yml"`
8. See error above

**Environment (please complete the following information):**
 - GPUs: Google Colab (free version)
- Configs:

data.jsonl:
```json
{"text": "prompt 1: completion 1"}
{"text": "prompt 2: completion 2"}
{"text": "prompt 3: completion 3"}
{"text": "prompt 4: completion 4"}
{"text": "prompt 5: completion 5"}
```

local_setup2.yml:
```yaml
# Suggested data paths when using GPT-NeoX locally
{
  "data-path": "/content/drive/MyDrive/Colab Notebooks/files/mydataset/mydataset",

  # or for weighted datasets:
  # "train-data-paths": ["data/enron/enron_text_document", "data/enron/enron_text_document"],
  # "test-data-paths": ["data/enron/enron_text_document", "data/enron/enron_text_document"],
  # "valid-data-paths": ["data/enron/enron_text_document", "data/enron/enron_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,
  "train_batch_size": 2,
  "vocab-file": "/content/drive/MyDrive/Colab Notebooks/files/gpt2-vocab.json",
  "merge-file": "/content/drive/MyDrive/Colab Notebooks/files/gpt2-merges.txt",

  "save": "checkpoints",
  "load": "checkpoints",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",git clo
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
```

Could you help me understanding what is happening?

**Comment by StellaAthena** [comment]
You should not be using this library in Google Colab. If you want to do inference using a model we trained using it, use the HuggingFace `transformers` library instead.
