### ISSUE TITLE
AssertionError: NeoXArgs.calculate_derived() (global_num_gpus / pp_size) / mp_size [(4 / 4) / 2] must be a whole number

### ISSUE THREAD

**Issue by wreiske** [EleutherAI/gpt-neox#757]
**Describe the bug**
AssertionError: NeoXArgs.calculate_derived() (global_num_gpus / pp_size) / mp_size [(4 / 4) / 2] must be a whole number

**To Reproduce**
1. Download the full_weights using the torrent file
2. Install Nvidia Docker
3. git clone https://github.com/EleutherAI/gpt-neox
4. move the full_weights/* to gpt-neox
5. Run `nvidia-docker run --rm -it -e NVIDIA_VISIBLE_DEVICES=0,1,2,3 --shm-size=1g --ulimit memlock=-1 --mount type=bind,src=$PWD,dst=/gpt-neox gpt-neox`
6. Run `./deepy.py generate.py ./configs/20B.yml`
7. Get this error https://github.com/EleutherAI/gpt-neox/issues/749
8. Replace save_interval with checkpoint_factor in the ./configs/20B.yml
9. Run `./deepy.py generate.py ./configs/20B.yml` again

```
mchorse@405289ad95c1:/gpt-neox$ ./deepy.py generate.py ./configs/20B.yml
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
NeoXArgs.from_ymls() ['./configs/20B.yml']INFO:root:NeoXArgs.calculate_derived() Total number of GPUs determined to be: 4
ERROR:root:NeoXArgs.calculate_derived() (global_num_gpus / pp_size) / mp_size [(4 / 4) / 2] must be a whole numberTraceback (most recent call last):
  File "./deepy.py", line 28, in <module>    neox_args = NeoXArgs.consume_deepy_args()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args    neox_args = cls.from_ymls(
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 218, in from_ymls
    return cls(**config)
  File "<string>", line 195, in __init__
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 123, in __post_init__    self.calculate_derived()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 706, in calculate_derived
    raise AssertionError(error_message)AssertionError: NeoXArgs.calculate_derived() (global_num_gpus / pp_size) / mp_size [(4 / 4) / 2] must be a whole number
```

**Expected behavior**
Run the model

**Environment (please complete the following information):**
- GPUs:
```
nvidia-smi 
Tue Dec 27 00:24:21 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:3D:00.0 Off |                    0 |
| N/A   31C    P0    33W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:3E:00.0 Off |                    0 |
| N/A   31C    P0    34W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:3F:00.0 Off |                    0 |
| N/A   31C    P0    33W / 250W |      0MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:40:00.0 Off |                    0 |
| N/A   31C    P0    34W / 250W |      0MiB / 32768MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

I had to edit the 20B.yml since /mnt/ssd-1 doesn't exist.
```
mchorse@8f51fb958c4d:/gpt-neox$ ./deepy.py generate.py ./configs/20B.yml -i ~/prompt.txt -o ~/sample_outputs.txt                                                
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!      
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "                                                                                       
NeoXArgs.from_ymls() ['./configs/20B.yml']                                                                                                                      
Traceback (most recent call last):                                                                                                                              
  File "./deepy.py", line 28, in <module>                                                                                                                       
    neox_args = NeoXArgs.consume_deepy_args()                                                                                                                     File "/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args                                                                        
    neox_args = cls.from_ymls(                                                                                                                                  
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 218, in from_ymls
    return cls(**config)
  File "<string>", line 195, in __init__ 
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 121, in __post_init__
    self.enable_logging()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 523, in enable_logging
    os.makedirs(self.log_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/ssd-1'
```

**Comment by wreiske** [comment]
I solved this by following https://www.youtube.com/watch?v=bAY85Om5O6A

specifically changing the `pipe-parallel-size` to 2 from 4.
