### ISSUE TITLE
The server socket has failed to bind to (errno: 98 - Address already in use)

### ISSUE THREAD

**Issue by githubbar** [EleutherAI/gpt-neox#768]
Running via sbatch, config:

  "launcher": "slurm",
  "deepspeed_slurm": true,
  "master_port": 29502,
  "distributed_backend": "nccl",

Result: Can't initialize torch

Trace:
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/generate.py", line 91, in <module>
    main()
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/megatron/utils.py", line 437, in setup_for_inference_or_eval
    initialize_megatron(neox_args)
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/megatron/initialize.py", line 75, in initialize_megatron
    finish_mpu_init()
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/megatron/initialize.py", line 51, in finish_mpu_init
    _initialize_distributed(neox_args=neox_args)
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/megatron/initialize.py", line 153, in _initialize_distributed
    distributed.init_distributed(
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/deepspeed/utils/distributed.py", line 49, in init_distributed
    torch.distributed.init_process_group(backend=dist_backend,
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/generate.py", line 91, in <module>
    main()
  File "/geode2/home/u070/oleykin/BigRed200/gpt-neox/generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 177, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29502 (errno: 98 - Address already in use). The server socket has failed to bind to su-aliases.head-bmc.cm.bigred200.uits.iu.edu:29502 (errno: 98 - Address already in use).
Traceback (most recent call last):the bug**

**Comment by StellaAthena** [comment]
This is an issue on your side, that may reflect other on-going processes or cluster-specific settings. Unfortunately it's not something we can really help with.

**Comment by sasaadi** [comment]
@githubbar can you please share how you solved the issue? thanks.

**Comment by githubbar** [comment]
Didn't solve it yet

**Comment by githubbar** [comment]
The issue was a missing hostfile.

This line in slurm script fixed it: 
scontrol show hostname $SLURM_JOB_NODELIST | sed  's/$/ slots=4/' > hostfile
