### ISSUE TITLE
ModuleNotFoundError: No module named 'best_download'

### ISSUE THREAD

**Issue by FayZ676** [EleutherAI/gpt-neox#769]
## Description
I just tried running `./deepy.py generate.py ./configs/20B.yml` from the README and `./deepy.py generate.py ./configs/20B.yml ./configs/text_generation.yml` after downloading the slim weights and got the following error.
```
Traceback (most recent call last):
  File "generate.py", line 91, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/home/faizi/gpt-neox/megatron/utils.py", line 416, in setup_for_inference_or_eval
    from megatron.training import setup_model_and_optimizer
  File "/home/faizi/gpt-neox/megatron/training.py", line 58, in <module>
    from eval_tasks import run_eval_harness
  File "/home/faizi/gpt-neox/eval_tasks/__init__.py", line 15, in <module>
    from .eval_adapter import EvalHarnessAdapter, run_eval_harness
  File "/home/faizi/gpt-neox/eval_tasks/eval_adapter.py", line 16, in <module>
    import best_download
ModuleNotFoundError: No module named 'best_download'
Killing subprocess 8712
Traceback (most recent call last):
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 179, in <module>
    main()
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 169, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 147, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
```

I only changed the pipe-parallel and model-parallel size in the `20B.yml` to be 1 and 1.

## To Reproduce
I had dependancy errors when trying to install everything directly from the `requirements.txt` file and had to make the following changes.
1. git clone https://github.com/EleutherAI/gpt-neox.git
2. sudo apt install mpich
3. pip install mpi4py
4. pip install protobuf==3.20
5. pip install -r requirements/requirements.txt
6. python ./megatron/fused_kernels/setup.py install # optional if not using fused kernels
7. wget --cut-dirs=5 -nH -r --no-parent --reject "index.html*" https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/ -P 20B_checkpoints8. 
8. `./deepy.py generate.py ./configs/20B.yml` or `./deepy.py generate.py ./configs/20B.yml ./configs/text_generation.yml`

**Environment (please complete the following information):**
 - GPUs: 1x A100
- Configs: 20B.yml

**Comment by FayZ676** [comment]
Fixed it via the following
```
git clone https://github.com/EleutherAI/best-download
pip install -r requirements-dev.txt
pytest
```
