### ISSUE TITLE
Finetuning 20B not working and bad traceback message

### ISSUE THREAD

**Issue by FayZ676** [EleutherAI/gpt-neox#770]
## Description
I double checked my CUDA install (`nvidia-smi` and `nvcc --version`) and all looks good. I don't get any other dependency errors either and am able to install everything. However, when I attempt to finetune 20B the process stops without any helpful traceback.

## To Reproduce
I run `python ./deepy.py train.py -d configs 20B.yml` and am using the `20B.yml` file and just adding `"finetune": true"`

## Expected behavior
```
WARNING: APEX not installed - defaulting to deepspeed's fused adamWARNING: APEX not installed - defaulting to deepspeed's fused adam

WARNING: APEX not installed - defaulting to deepspeed's fused adam
WARNING: APEX not installed - defaulting to deepspeed's fused adam
WARNING: APEX not installed - defaulting to deepspeed's fused adam
Configuring Optimizer type: Adam with params: {'lr': 9.7e-05, 'betas': [0.9, 0.95], 'eps': 1e-08}
WARNING: APEX not installed - defaulting to deepspeed's fused adam
WARNING: APEX not installed - defaulting to deepspeed's fused adam
WARNING: APEX not installed - defaulting to deepspeed's fused adam
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Using /home/faizi/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/faizi/.cache/torch_extensions/py38_cu117/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.1894216537475586 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.20286035537719727 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.2030327320098877 seconds
Loading extension module fused_adam...
Time to load fused_adam op: 0.20239520072937012 seconds
Loading extension module fused_adam...
Loading extension module fused_adam...
Time to load fused_adam op: 0.20412898063659668 seconds
Time to load fused_adam op: 0.20318007469177246 seconds
Loading extension module fused_adam...
Loading extension module fused_adam...
Time to load fused_adam op: 0.20298457145690918 seconds
Time to load fused_adam op: 0.2037966251373291 seconds
Killing subprocess 14156
Killing subprocess 14157
Killing subprocess 14158
Killing subprocess 14159
Killing subprocess 14160
Killing subprocess 14161
Killing subprocess 14162
Killing subprocess 14163
Traceback (most recent call last):
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 179, in <module>
    main()
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 169, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/faizi/miniconda3/envs/neox/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 147, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
```

**Environment (please complete the following information):**
 - GPUs: 8x A100 40GB

**Comment by StellaAthena** [comment]
Can you launch training? If not, this is a local set-up problem.
