### ISSUE TITLE
Cannot find the vocabulary file

### ISSUE THREAD

**Issue by LostSpirit1307** [EleutherAI/gpt-neox#776]
The following error occured when trying to run "./deepy.py generate.py ./configs/20B.yml"

Traceback (most recent call last):                                                                               
  File "generate.py", line 89, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/utils.py", line 428, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/neox_arguments/arguments.py", line 138, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 46, in build_tokenizer
Traceback (most recent call last):
  File "generate.py", line 89, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/utils.py", line 428, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/neox_arguments/arguments.py", line 138, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 46, in build_tokenizer
        tokenizer = HFTokenizer(args.vocab_file)    tokenizer = HFTokenizer(args.vocab_file)
tokenizer = HFTokenizer(args.vocab_file)

  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
tokenizer = HFTokenizer(args.vocab_file)  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer
.py", line 228, in __init__

  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception    : self.tokenizer = Tokenizer.from_file(vocab_file)No such file or directory (os error 2)

It seems like the path of something is not correct.

**Comment by StellaAthena** [comment]
Yes, you need to download the vocab file as discussed in the readme.

**Comment by LostSpirit1307** [comment]
I'm sorry the issue still not solved. In fact, I have downloaded the vocabulary file "20B_tokenizer.json" and try to run generate.py, not intend to train or finetune. I can provide more information about this issue:

[2023-01-25 04:00:56,372] [INFO] [launch.py:82:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3]}                
[2023-01-25 04:00:56,372] [INFO] [launch.py:88:main] nnodes=1, num_local_procs=4, node_rank=0
[2023-01-25 04:00:56,372] [INFO] [launch.py:103:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1,
2, 3]})
[2023-01-25 04:00:56,372] [INFO] [launch.py:104:main] dist_world_size=4
[2023-01-25 04:00:56,373] [INFO] [launch.py:112:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3
NeoXArgs.configure_distributed_args() using world size: 4 and model-parallel size: 1
> building HFTokenizer tokenizer ...
Traceback (most recent call last):
  File "generate.py", line 89, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/utils.py", line 428, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/neox_arguments/arguments.py", line 138, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 46, in build_tokenizer
    tokenizer = HFTokenizer(args.vocab_file)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception: No such file or directory (os error 2)
Traceback (most recent call last):
  File "generate.py", line 89, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/utils.py", line 428, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/neox_arguments/arguments.py", line 138, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 46, in build_tokenizer
    tokenizer = HFTokenizer(args.vocab_file)                                                                     [122/1827]
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception: No such file or directory (os error 2)
Traceback (most recent call last):
  File "generate.py", line 89, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/utils.py", line 428, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/neox_arguments/arguments.py", line 138, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 46, in build_tokenizer
    tokenizer = HFTokenizer(args.vocab_file)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception: No such file or directory (os error 2)
Traceback (most recent call last):
  File "generate.py", line 89, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/utils.py", line 428, in setup_for_inference_or_eval
    neox_args.build_tokenizer()
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/neox_arguments/arguments.py", line 138, in build_tokenizer
    self.tokenizer = build_tokenizer(self)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 46, in build_tokenizer
    tokenizer = HFTokenizer(args.vocab_file)
  File "/opt/data/private/LostSpirit/GPT-Neox/gpt-neox/megatron/tokenizer/tokenizer.py", line 228, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception: No such file or directory (os error 2)
Killing subprocess 11701                                                                                          [90/1827]
Killing subprocess 11702
Killing subprocess 11703
Killing subprocess 11704
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 179, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 169, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/opt/conda/lib/python3.8/site-packages/deepspeed/launcher/launch.py", line 147, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)

Thank you for your answering and patience!

**Comment by StellaAthena** [comment]
Your code can't find the file you downloaded. I heavily recommend making sure that `vocab_file` is pointing to the correct location. It's hard to come up with another explanation.
