### ISSUE TITLE
Cannot run inference on Linux - `save_iters` issue

### ISSUE THREAD

**Issue by bytesuji** [EleutherAI/gpt-neox#796]
**Describe the bug**
I downloaded the "Slim weights" from the README and cloned the repo. I executed the command:

```
./deepy.py generate.py ../neox/20B_checkpoints/configs/20B.yml
```

It hangs for a few seconds then outputs the following error:

```
Traceback (most recent call last):
  File "./deepy.py", line 28, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args
    neox_args = cls.from_ymls(
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 218, in from_ymls
    return cls(**config)
  File "<string>", line 196, in __init__
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 123, in __post_init__
    self.calculate_derived()
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 758, in calculate_derived
    "save_iters": save_iters,
UnboundLocalError: local variable 'save_iters' referenced before assignment
```

**To Reproduce**
I'm using the default slim weights and the unmodified repo code.

**Expected behavior**
Model should run

**Proposed solution**
I tried setting `save_iters = []` in the relevant part of the code to circumvent this problem, but I got another error:

```
INFO:root:NeoXArgs.calculate_derived() Total number of GPUs determined to be: 8
ERROR:root:NeoXArgs.validate_values() checkpoint_factor or extra_save_iters must be defined if save is defined
Traceback (most recent call last):
  File "./deepy.py", line 28, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args
    neox_args = cls.from_ymls(
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 218, in from_ymls
    return cls(**config)
  File "<string>", line 196, in __init__
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 131, in __post_init__
    if not self.validate_values():
  File "/home/ubuntu/gpt-neox/megatron/neox_arguments/arguments.py", line 961, in validate_values
    raise ValueError(error_message)
ValueError: NeoXArgs.validate_values() checkpoint_factor or extra_save_iters must be defined if save is defined
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - GPUs: 8x Tesla K80s
- Configs:
  - NVIDIA Driver Version: 470.161.03   
  - CUDA Version: 11.4 
  - Python 3.8
  - Kernel 5.15.0-1030-aws

**Additional context**
I have two separate directories, `~/neox` which contains the files from the "Slim weights" link in the README, and `~/gpt-neox` which a clone of this repo.

**Comment by bytesuji** [comment]
I got this to work by moving `20B_checkpoints` from the slim weights download into the repo and specifying `configs/20B.yml` from the repository rather than from the weights download.
