### ISSUE TITLE
deepspeed.ops.op_builder

### ISSUE THREAD

**Issue by zscwind** [EleutherAI/gpt-neox#797]
**Describe the bug**
>>> import deepspeed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/project/llm/DeeperSpeed/deepspeed/__init__.py", line 7, in <module>
    from . import ops
  File "/data/project/llm/DeeperSpeed/deepspeed/ops/__init__.py", line 1, in <module>
    from . import adam
  File "/data/project/llm/DeeperSpeed/deepspeed/ops/adam/__init__.py", line 1, in <module>
    from .cpu_adam import DeepSpeedCPUAdam
  File "/data/project/llm/DeeperSpeed/deepspeed/ops/adam/cpu_adam.py", line 9, in <module>
    from ..op_builder import CPUAdamBuilder
ModuleNotFoundError: No module named 'deepspeed.ops.op_builder'

**To Reproduce**
1. `git clone https://github.com/EleutherAI/DeeperSpeed`
2. `git checkout eb7f5cff`
3. `pip install -r requirements/requirements.txt`
4. `pip install .`
5. `python -c 'import deepspeed'`

**Expected behavior**
I want to install deepspeed successfully and it works correctly.

**Proposed solution**
If you have an idea for how we can fix this problem, describe it here.

**Screenshots**

**Environment (please complete the following information):**
 - CUDA 11.3
 - torch 1.13.0.dev20220727+cu113
 - python 3.8.16

**Additional context**

**Comment by StellaAthena** [comment]
This issue is also occurring here: https://github.com/EleutherAI/gpt-neox/issues/785#issuecomment-1433038136

**Comment by Quentin-Anthony** [comment]
@zscwind -- Can you try again with the latest [DeeperSpeed](https://github.com/EleutherAI/DeeperSpeed)? I can't seem to reproduce your error on my system.

**Comment by haileyschoelkopf** [comment]
I've seen this error a bunch on my old academic lab's machine. 

Generally the root cause for me has been because either Deepspeed doesn't know where to find CUDA when you install it or because torch isn't playing nice with whatever cuda version you have. 

For example, one fix I've had was to set these variables in the terminal before installing Deepspeed:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.1/lib64
export PATH=$PATH:/usr/local/cuda-11.1/bin
export CUDA_HOME=/usr/local/cuda-11.1
```
where these point to your installation of CUDA 11.3 on the machine.

It sounds like you have Pytorch with the proper cuda version installed, but I've also seen Torch cause problems when you don't explicitly install a version shipped with the correct cuda version: `python -c "import torch; print(torch.version.cuda)"` can sanity check that the output is indeed 11.3

**Comment by Quentin-Anthony** [comment]
Closing this due to inactivity. Feel free to re-open if you'd like to continue debugging @zscwind
