### ISSUE TITLE
fused_kernels not installed

### ISSUE THREAD

**Issue by NikBoy0809** [EleutherAI/gpt-neox#801]
**Describe the bug**
**fused_kernels gives an error during installation**
**Console output:**
running install
running bdist_egg
running egg_info
writing fused_kernels.egg-info/PKG-INFO
writing dependency_links to fused_kernels.egg-info/dependency_links.txt
writing top-level names to fused_kernels.egg-info/top_level.txt
adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
reading manifest file 'fused_kernels.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fused_kernels.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'scaled_upper_triang_masked_softmax_cuda' extension
Emitting ninja build file /home/apely/gpt-neox/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/apely/gpt-neox/build/temp.linux-x86_64-3.8/home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.o.d -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/TH -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/THC -I/home/apely/gpt-neox/python/da/include -I/usr/include/python3.8 -c -c /home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o /home/apely/gpt-neox/build/temp.linux-x86_64-3.8/home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14

**FAILED:** /home/apely/gpt-neox/build/temp.linux-x86_64-3.8/home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.o
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output /home/apely/gpt-neox/build/temp.linux-x86_64-3.8/home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.o.d -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/TH -I/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/THC -I/home/apely/gpt-neox/python/da/include -I/usr/include/python3.8 -c -c /home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.cu -o /home/apely/gpt-neox/build/temp.linux-x86_64-3.8/home/apely/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -gencode arch=compute_70,code=sm_70 --use_fast_math -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda -gencode arch=compute_80,code=sm_80 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=scaled_upper_triang_masked_softmax_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(110): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(110): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(110): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(110): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(110): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(110): warning #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead

/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./megatron/fused_kernels/setup.py", line 43, in <module>
    setup(
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/apely/gpt-neox/python/da/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**To Reproduce**
1.git clone https://github.com/EleutherAI/gpt-neox.git
2.cd gpt-neox
3.pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
4.pip install -r requirements/requirements.txt
5.python ./megatron/fused_kernels/setup.py install

**Environment (please complete the following information):**
- CUDA:11.1
- torch:1.8.1
- python 3.8.16

**Additional context**
I'm try to switch torch version

**Comment by dengliangjun** [comment]
have you solved this problem?

**Comment by NikBoy0809** [comment]
> have you solved this problem?
> glad to hear from your solution, thanks, I meet the same probblems.
nope, i have no idea how to solve this

**Comment by Quentin-Anthony** [comment]
Yep I've seen this error. It's caused because your CUDA (`nvcc`) version doesn't properly handle the `noexcept(_Handler<_Functor>::template _S_nothrow_init<_Functor>())` lines in all gcc versions 11.3.0 or newer.

Your options are to either :
1. If your gcc installation is editable, simply comment out the lines containing `noexcept(_Handler<_Functor>::template _S_nothrow_init<_Functor>())`. E.g. for gcc v11.3.0, comment out https://github.com/gcc-mirror/gcc/blob/releases/gcc-11.3.0/libstdc%2B%2B-v3/include/bits/std_function.h#L436 and https://github.com/gcc-mirror/gcc/blob/releases/gcc-11.3.0/libstdc%2B%2B-v3/include/bits/std_function.h#L531, which you can find by running `which g++`, then looking in `<gcc-prefix>/bits/std_function.h` (for user gcc installs, this is usually at `/usr/include/c++/*/bits/std_function.h`). Open with your favorite editor and comment out the two problematic lines.
2. Downgrade to a gcc version below 11.3.0, befor the lines were introduced in https://github.com/gcc-mirror/gcc/commit/d38d26be33aba5d4c12429478375a47c474124d2 (e.g. you can see they don't exist in https://github.com/gcc-mirror/gcc/blob/releases/gcc-11.2.0/libstdc%2B%2B-v3/include/bits/std_function.h)
3. Upgrade to CUDA 11.6.2+, which fixed the incompatibility
