### ISSUE TITLE
Unable to run generate text

### ISSUE THREAD

**Issue by hax4usincupad** [EleutherAI/gpt-neox#885]
**Describe the bug**
 ```
File "generate.py", line 91, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/home/ubuntu/gpt-neox/megatron/utils.py", line 443, in setup_for_inference_or_eval
    model, _, _ = setup_model_and_optimizer(
  File "/home/ubuntu/gpt-neox/megatron/training.py", line 621, in setup_model_and_optimizer
    model, optimizer, _, lr_scheduler = deepspeed.initialize(
  File "/home/ubuntu/.neox3.8/lib/python3.8/site-packages/deepspeed/__init__.py", line 137, in initialize
    assert config is None, "Not sure how to proceed, we were given deepspeed configs in the deepspeed arguments and deepspeed.initialize() function call"
AssertionError: Not sure how to proceed, we were given deepspeed configs in the deepspeed arguments and deepspeed.initialize() function call
```

**To Reproduce**
Just execute
` ./deepy.py generate.py -d configs bf16_125M.yml local_setup.yml`

**Environment (please complete the following information):**
 - GPUs: 4
- Configs:

**Comment by StellaAthena** [comment]
@hax4usincupad where did you get model weights to run with this c? Did you train your own model in bf16?

**Comment by hiroshi-matsuda-rit** [comment]
Try to downgrade the deepspeed to version 0.8.x. @hax4usincupad 
`pip install -U "deepspeed<=0.9.0"`

**Comment by StellaAthena** [comment]
> Try downgrading the deepspeed to version 0.8.x. @hax4usincupad
> `pip install -U "deepspeed<0.9.0"`

This library is designed to use a custom fork of DeepSpeed: https://github.com/EleutherAI/DeeperSpeed. Using the `main` DS may cause issues

**Comment by garrett361** [comment]
> This library is designed to use a custom fork of DeepSpeed...

@StellaAthena I'm hitting the same issue as OP and I'm a little confused about the gpt-neox/DeeperSpeed connection: where in the gpt-neox code base is DeeperSpeed being used specifically?

In particular, I see very few references to DeeperSpeed in the code base and `requirements/requirements.txt` seems to just pip install the usual `deepspeed`. I'm unable to see how DeeperSpeed makes it way into the Docker image, which is how I'm trying to run gpt-neox. Can you clarify?  Thanks!

**Comment by drjtryu** [comment]
I want to run the text generation example, but the following error occurs.

--> size mismatch for word_embeddings.weight: copying a param with shape torch.Size([25216, 6144]) from checkpoint, the shape in current model is torch.Size([12672, 6144]).

-----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "generate.py", line 91, in <module>
    main()
  File "generate.py", line 33, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=True)
  File "/deepspeed/megatron/utils.py", line 440, in setup_for_inference_or_eval
    model, _, _ = setup_model_and_optimizer(
  File "/deepspeed/megatron/training.py", line 447, in setup_model_and_optimizer
    neox_args.iteration = load_checkpoint(
  File "/deepspeed/megatron/checkpointing.py", line 239, in load_checkpoint
    checkpoint_name, state_dict = model.load_checkpoint(
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1523, in load_checkpoint
    load_path, client_states = self._load_checkpoint(load_dir,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1558, in _load_checkpoint
    self.load_module_state_dict(state_dict=checkpoint['module'],
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/pipe/engine.py", line 1278, in load_module_state_dict
    self.module.load_state_dir(load_dir=self._curr_ckpt_path, strict=strict)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/pipe/module.py", line 571, in load_state_dir
    layer.load_state_dict(torch.load(model_ckpt_path,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EmbeddingPipe:
        size mismatch for word_embeddings.weight: copying a param with shape torch.Size([25216, 6144]) from checkpoint, the shape in current model is torch.Size([12672, 6144]).
Traceback (most recent call last):

**Comment by StellaAthena** [comment]
Can you pull from `main` and test to see if the recently merged fix solves your issue?
